### ISSUE TITLE
Problem with vendoring

### ISSUE THREAD

**Issue by hwsoderlund** [revel/cmd#169]
I tried to update revel/cmd to the latest version just now, and there seems to be a problem when the modules package is situated in the vendor folder. This is what the output says:

> Go Compilation Error (in app/tmp/run/run.go:22): must be imported as github.com/revel/modules/jobs/app/controllers

And this is the line it complains about:

```
controllers0 "mindoktor.io/mindoktor/vendor/github.com/revel/modules/jobs/app/controllers"
```

I'm not sure exactly what the problem is, so I don't think I will be able to help with solving it.

**Comment by hwsoderlund** [comment]
I would very much appreciate some feedback here. This is preventing us from upgrading to the latest version.

**Comment by notzippy** [comment]
Hi sorry for the delay - holidays and busy time at work. Hmm that go import path looks completely wrong. Where is your app folder with respect to your vendor folder ?

**Comment by hwsoderlund** [comment]
Hi, and thanks for getting back. The vendor folder is actually one level up from the revel root folder. So pretending our revel application is here:

```
mindoktor.io/mindoktor/REVELAPP
```

Then the vendor folder is here:

```
mindoktor.io/mindoktor/vendor
```

So you think the location of the vendor folder could be a problem? Unfortunately I don't think we can move things around, not easily anyway.

**Comment by hwsoderlund** [comment]
Oh, and just FYI, this worked fine in version 0.20.

**Comment by notzippy** [comment]
Revel now uses go.mod
